# Generated by Django 5.2.7 on 2025-10-30 12:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название умения', max_length=200, unique=True, verbose_name='Название')),
                ('category', models.CharField(choices=[('TECH', 'Техническое'), ('METHOD', 'Методическое'), ('SOFT', 'Софт-умение'), ('DOMAIN', 'Предметное')], db_index=True, help_text='Категория, к которой относится умение', max_length=10, verbose_name='Категория')),
                ('description', models.TextField(blank=True, help_text='Подробное описание умения и его применения', verbose_name='Описание')),
                ('frequency', models.IntegerField(db_index=True, default=0, help_text='Количество упоминаний умения в вакансиях', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Частота упоминаний')),
                ('relevance', models.FloatField(db_index=True, default=1.0, help_text='Коэффициент актуальности умения (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Релевантность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Умение',
                'verbose_name_plural': 'Умения',
                'db_table': 'cc_sm_skill',
                'ordering': ['-frequency', 'name'],
                'indexes': [models.Index(fields=['-frequency', 'category'], name='cc_skill_freq_cat_idx'), models.Index(fields=['category', '-relevance'], name='cc_skill_cat_rel_idx')],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название технологии', max_length=200, unique=True, verbose_name='Название')),
                ('category', models.CharField(choices=[('LANG', 'Язык программирования'), ('FRAMEWORK', 'Фреймворк'), ('LIBRARY', 'Библиотека'), ('TOOL', 'Инструмент'), ('DB', 'База данных'), ('PLATFORM', 'Платформа'), ('PROTOCOL', 'Протокол'), ('SERVICE', 'Сервис')], db_index=True, help_text='Категория технологии', max_length=15, verbose_name='Категория')),
                ('description', models.TextField(blank=True, help_text='Подробное описание технологии', verbose_name='Описание')),
                ('popularity', models.IntegerField(db_index=True, default=0, help_text='Показатель популярности технологии', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Популярность')),
                ('relevance', models.FloatField(db_index=True, default=1.0, help_text='Коэффициент актуальности технологии (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Релевантность')),
                ('occurrence_count', models.IntegerField(default=0, help_text='Количество упоминаний в вакансиях', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество упоминаний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent_tech', models.ForeignKey(blank=True, help_text='Родительская технология в иерархии (например, React для Next.js)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_technologies', to='competence_core_skill_map.technology', verbose_name='Родительская технология')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'db_table': 'cc_sm_technology',
                'ordering': ['-popularity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.FloatField(default=1.0, help_text='Насколько релевантна данная технология для данного умения (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Релевантность связи')),
                ('usage_frequency', models.IntegerField(default=0, help_text='Количество раз, когда умение и технология встречались вместе', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Частота совместного использования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('skill', models.ForeignKey(help_text='Умение, связанное с технологией', on_delete=django.db.models.deletion.CASCADE, related_name='skill_technologies', to='competence_core_skill_map.skill', verbose_name='Умение')),
                ('technology', models.ForeignKey(help_text='Технология, связанная с умением', on_delete=django.db.models.deletion.CASCADE, related_name='technology_skills', to='competence_core_skill_map.technology', verbose_name='Технология')),
            ],
            options={
                'verbose_name': 'Связь умение-технология',
                'verbose_name_plural': 'Связи умение-технология',
                'db_table': 'cc_sm_skill_technology',
                'ordering': ['-relevance', '-usage_frequency'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, help_text='Альтернативное или сокращенное название технологии', max_length=200, verbose_name='Альтернативное название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('technology', models.ForeignKey(help_text='Технология, для которой указан альтернативное название', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='competence_core_skill_map.technology', verbose_name='Технология')),
            ],
            options={
                'verbose_name': 'Альтернативное название технологии',
                'verbose_name_plural': 'Альтернативные названия технологий',
                'db_table': 'cc_sm_technology_alias',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='SkillSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(db_index=True, help_text='Альтернативное название умения', max_length=200, verbose_name='Синоним')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('skill', models.ForeignKey(help_text='Умение, для которого указан синоним', on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='competence_core_skill_map.skill', verbose_name='Умение')),
            ],
            options={
                'verbose_name': 'Синоним умения',
                'verbose_name_plural': 'Синонимы умений',
                'db_table': 'cc_sm_skill_synonym',
                'ordering': ['synonym'],
                'indexes': [models.Index(fields=['synonym'], name='cc_skill_syn_idx'), models.Index(fields=['skill', 'synonym'], name='cc_skill_syn_skill_idx')],
                'unique_together': {('skill', 'synonym')},
            },
        ),
        migrations.AddIndex(
            model_name='technology',
            index=models.Index(fields=['-popularity', 'category'], name='cc_tech_pop_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='technology',
            index=models.Index(fields=['category', '-relevance'], name='cc_tech_cat_rel_idx'),
        ),
        migrations.AddIndex(
            model_name='skilltechnology',
            index=models.Index(fields=['skill', '-relevance'], name='cc_skill_tech_skill_idx'),
        ),
        migrations.AddIndex(
            model_name='skilltechnology',
            index=models.Index(fields=['technology', '-relevance'], name='cc_skill_tech_tech_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skilltechnology',
            unique_together={('skill', 'technology')},
        ),
        migrations.AddIndex(
            model_name='technologyalias',
            index=models.Index(fields=['alias'], name='cc_tech_alias_idx'),
        ),
        migrations.AddIndex(
            model_name='technologyalias',
            index=models.Index(fields=['technology', 'alias'], name='cc_tech_alias_tech_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technologyalias',
            unique_together={('technology', 'alias')},
        ),
    ]
