# Generated by Django 5.2.7 on 2025-10-30 12:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competence_core_skill_map', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название компетенции', max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Подробное описание компетенции и её применения', verbose_name='Описание')),
                ('level', models.CharField(blank=True, choices=[('JUNIOR', 'Junior'), ('MIDDLE', 'Middle'), ('SENIOR', 'Senior'), ('EXPERT', 'Expert')], db_index=True, help_text='Профессиональный уровень компетенции', max_length=10, verbose_name='Уровень')),
                ('popularity', models.IntegerField(db_index=True, default=0, help_text='Показатель популярности компетенции в вакансиях', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Популярность')),
                ('relevance', models.FloatField(db_index=True, default=1.0, help_text='Коэффициент актуальности компетенции (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Релевантность')),
                ('is_core', models.BooleanField(db_index=True, default=True, help_text='Является ли компетенция ключевой для профессии', verbose_name='Ключевая компетенция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
                'db_table': 'cc_competence',
                'ordering': ['-popularity', 'name'],
                'indexes': [models.Index(fields=['-popularity', 'level'], name='cc_comp_pop_level_idx'), models.Index(fields=['is_core', '-relevance'], name='cc_comp_core_rel_idx')],
            },
        ),
        migrations.CreateModel(
            name='VacancyCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='Приоритет компетенции (чем меньше число, тем выше приоритет)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Приоритет')),
                ('required_level', models.CharField(blank=True, choices=[('JUNIOR', 'Junior'), ('MIDDLE', 'Middle'), ('SENIOR', 'Senior'), ('EXPERT', 'Expert')], help_text='Минимальный требуемый уровень компетенции', max_length=10, verbose_name='Требуемый уровень')),
                ('is_mandatory', models.BooleanField(db_index=True, default=True, help_text='Является ли компетенция обязательной для вакансии', verbose_name='Обязательная компетенция')),
                ('weight', models.FloatField(default=1.0, help_text='Вес компетенции при подборе и оценке кандидатов (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Вес компетенции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('competence', models.ForeignKey(help_text='Требуемая компетенция', on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_competences', to='competence_core.competence', verbose_name='Компетенция')),
            ],
            options={
                'verbose_name': 'Компетенция вакансии',
                'verbose_name_plural': 'Компетенции вакансий',
                'db_table': 'cc_vacancy_competence',
                'ordering': ['priority', '-weight'],
            },
        ),
        migrations.CreateModel(
            name='VacancyCompetenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='Идентификатор вакансии', verbose_name='ID вакансии')),
                ('vacancy_title', models.CharField(db_index=True, help_text='Кэшированное название вакансии для быстрого доступа', max_length=500, verbose_name='Название вакансии')),
                ('vacancy_source', models.CharField(blank=True, db_index=True, help_text='Источник вакансии (HeadHunter, Habr Career, SuperJob и т.д.)', max_length=50, verbose_name='Источник вакансии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('competences', models.ManyToManyField(related_name='vacancy_profiles', through='competence_core.VacancyCompetence', to='competence_core.competence', verbose_name='Компетенции')),
                ('content_type', models.ForeignKey(help_text='Модель вакансии (HeadHunter, Habr Career и т.д.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип вакансии')),
            ],
            options={
                'verbose_name': 'Профиль компетенций вакансии',
                'verbose_name_plural': 'Профили компетенций вакансий',
                'db_table': 'cc_vacancy_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vacancycompetence',
            name='vacancy_profile',
            field=models.ForeignKey(help_text='Профиль компетенций вакансии', on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_competences', to='competence_core.vacancycompetenceprofile', verbose_name='Профиль вакансии'),
        ),
        migrations.CreateModel(
            name='CompetenceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.FloatField(default=1.0, help_text='Важность компонента для компетенции (0.0-1.0, где 1.0 - критически важный)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Важность компонента')),
                ('required_level', models.CharField(blank=True, choices=[('JUNIOR', 'Junior'), ('MIDDLE', 'Middle'), ('SENIOR', 'Senior'), ('EXPERT', 'Expert')], help_text='Минимальный уровень владения умением для данной компетенции', max_length=10, verbose_name='Требуемый уровень владения')),
                ('weight', models.FloatField(default=1.0, help_text='Относительный вес при расчете общего уровня компетенции', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Вес компонента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('competence', models.ForeignKey(help_text='Компетенция, к которой относится компонент', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='competence_core.competence', verbose_name='Компетенция')),
                ('skill', models.ForeignKey(help_text='Базовое умение компонента', on_delete=django.db.models.deletion.CASCADE, related_name='competence_components', to='competence_core_skill_map.skill', verbose_name='Умение')),
                ('skill_technology', models.ForeignKey(blank=True, help_text='Опциональная связка умение-технология для более точного определения компонента', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence_components', to='competence_core_skill_map.skilltechnology', verbose_name='Связь умение-технология')),
            ],
            options={
                'verbose_name': 'Компонент компетенции',
                'verbose_name_plural': 'Компоненты компетенций',
                'db_table': 'cc_competence_component',
                'ordering': ['-importance', '-weight'],
                'indexes': [models.Index(fields=['competence', '-importance'], name='cc_comp_comp_imp_idx'), models.Index(fields=['skill', 'skill_technology'], name='cc_comp_comp_skill_idx'), models.Index(fields=['competence', 'skill'], name='cc_comp_comp_cs_idx')],
                'unique_together': {('competence', 'skill', 'skill_technology')},
            },
        ),
        migrations.AddIndex(
            model_name='vacancycompetenceprofile',
            index=models.Index(fields=['content_type', 'object_id'], name='cc_vac_prof_ct_oid_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancycompetenceprofile',
            index=models.Index(fields=['vacancy_source', '-created_at'], name='cc_vac_prof_src_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancycompetenceprofile',
            index=models.Index(fields=['-created_at'], name='cc_vac_prof_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancycompetenceprofile',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='vacancycompetence',
            index=models.Index(fields=['vacancy_profile', 'priority'], name='cc_vac_comp_prof_pri_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancycompetence',
            index=models.Index(fields=['competence', '-weight'], name='cc_vac_comp_comp_w_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancycompetence',
            index=models.Index(fields=['is_mandatory', 'priority'], name='cc_vac_comp_mand_pri_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancycompetence',
            unique_together={('vacancy_profile', 'competence')},
        ),
    ]
